### ISSUE TITLE
not issues,just some request maybe.

### ISSUE THREAD

**Issue by nelson7o7** [kalanakt/Renamer-Bot#1]
Can you add converting options?like video to file,file to video without renaming it?

**Comment by kalanakt** [comment]
already added. use /mode command to change video mode or file mode.
if you convert the file to video, bot ask video name give any name it's no matter
but you convert the video to file you should give the file name

**Comment by nelson7o7** [comment]
i mean,converting the file without need to give new name,make it use the file default name without need to give new name?

**Comment by kalanakt** [comment]
it's not possible.
