### ISSUE TITLE
Request for help

### ISSUE THREAD

**Issue by nelson7o7** [kalanakt/Renamer-Bot#8]
would you mind take a look on this repo and tell me which code should be change to make it similar to your bot that generate thumbnail by default (when converting to file) even no thumbnail was saved?,just for my personal use only,really appreciate it if you can help me 
https://github.com/nelson7o7/AIOM-TG-RENAME-BOT

**Comment by kalanakt** [comment]
https://github.com/kalanakt/renamer/plugins/rename.py line 114


in that repo : https://github.com/nelson7o7/AIOM-TG-RENAME-BOT/blob/main/root/utils/uploader.py
line 79 

change it like this,


else:
            try:
                thumbnail_location = await take_screen_shot(new_file_location, os.path.dirname(os.path.abspath(new_file_location)), random.randint(0, duration - 1))
            except Exception as e:
                logger.error(e)
                thumbnail_location = None

**Comment by nelson7o7** [comment]
Bot not working,.i have try with change "thumbnail_location" as "thumb_location" and "thumb_image_path" and more, but no luck
![10](https://user-images.githubusercontent.com/89224036/147704614-86893a6f-85ee-4d9e-95a6-647c90b4e4aa.PNG)
![6](https://user-images.githubusercontent.com/89224036/147704765-822af356-ac3f-4547-8ce3-7b3a8f440371.PNG)
